highlighter: rouge
permalink: /posts/:title.html

title: Kylexlau's Weblog
author:
  name: kyle lau
  email: kylexlau@gmail.com
  github: kylexlau
  twitter: kylexlau

production_url: http://kyle.xlau.org