permalink: /posts/:title.html
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

title: Kylexlau's Weblog
author:
  name: kyle lau
  email: kylexlau@gmail.com
  github: kylexlau
  twitter: kylexlau

production_url: http://kyle.xlau.org